"""
Django settings for first_try project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-@*a5@81k71vh49b-c4k($7u736i&t7fmlfz@)0a6px$nu#5$gi"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "mysite",
    "registration",
    "captcha",
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.facebook",
    "easy_thumbnails",
    "filer",
    "mptt",
    "cart",
    "paypal.standard.ipn",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "first_try.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR/"template"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "cart.context_processor.cart_total_amount",
            ],
        },
    },
]

WSGI_APPLICATION = "first_try.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "httpresponse",
        "USER": "root",
        "PASSWORD":"sue47809",
        "HOST": "127.0.0.1",
        "Port": '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]

SITE_ID=1
LOGIN_REDIRECT_URL="/"

AUTHENTICATION_BACKENDS=[
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# SMTP Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  #SMTP伺服器
EMAIL_PORT = 587  #TLS通訊埠號
EMAIL_USE_TLS = True  #開啟TLS(傳輸層安全性)
EMAIL_HOST_USER = 'judy5566675@gmail.com'  #寄件者電子郵件
EMAIL_HOST_PASSWORD = 'qdsj rwuk ardb msbx'  #Gmail應用程式的密碼

GOOGLE_RECAPTCHA_SECRET_KEY= '6LcotrUpAAAAAOZTMJI3Kse42kZbc4Snb5P17WEC'

THUMBNAIL_PROCESSORS=(
    "easy_thumbnails.processors.colorspace",
    "easy_thumbnails.processors.autocrop",
    "filer.thumbnail_processors.scale_and_crop_with_subject_location",
    "easy_thumbnails.processors.filters",
)

FILER_STORAGES={
    "public":{
        "main":{
            'ENGINE':'filer.storage.PublicFileSystemStorage',
            'OPTIONS':{
                'location':os.path.join(BASE_DIR,'/media/filer'),
                'base_url':'/media/filer/',
            },
            'UPLOAD_TO':'filer.utils.generate_filename.randomized',
            'UPLOAD_TO_PREFIX':'filer_public',
        },
        'thumbnails':{
            'ENGINE':'filer.storage.PublicFileSystemStorage',
            'OPTIONS':{
                'location':os.path.join(BASE_DIR,'/media/filer_thumbnails'),
                'base_url':'/media/filer_thumbnails/',
            },
        },
    },
    'private':{
        'main':{
            'ENGINE':'filer.storage.PublicFileSystemStorage',
            'OPTIONS':{
                'location':os.path.join(BASE_DIR,'/smedia/filer'),
                'base_url':'/smedia/filer/',
            },
            'UPLOAD_TO':'filer.utils.generate_filename.randomized',
            'UPLOAD_TO_PREFIX':'filer_public',
        },
    'thumbnails':{
            'ENGINE':'filer.storage.PublicFileSystemStorage',
            'OPTIONS':{
                'location':os.path.join(BASE_DIR,'/smedia/filer_thumbnails'),
                'base_url':'/smedia/filer_thumbnails/',
            },
        },
    },
}

MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'media')

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "zh-hant"

TIME_ZONE = "Asia/Taipei"

USE_I18N = True

USE_TZ = True

LOGIN_REDIRECT_URL="http://127.0.0.1:8000/admin/logout/"

CAPTCHA_TIMEOUT = 60

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR/'staticfiles'
STATICFILES_DIRS=[
    BASE_DIR/"static"
]

CART_SESSION_ID='cart'

PAYPAL_TEST=True

PAYPAL_RECEIVER_EMAIL="judy5566675@gmail.com"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
