# Generated by Django 5.0.1 on 2024-02-26 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Phone_Maker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Maker", models.CharField(max_length=200)),
                ("Country", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Phone_Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Model", models.CharField(max_length=200)),
                ("URL", models.URLField()),
                (
                    "Maker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mysite.phone_maker",
                    ),
                ),
            ],
        ),
    ]
