# Generated by Django 5.0.1 on 2024-02-26 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0002_phone_maker_phone_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Phone_Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Description", models.CharField(max_length=200)),
                ("Price", models.PositiveIntegerField()),
                ("Quantity", models.PositiveIntegerField()),
                ("Img", models.URLField()),
                (
                    "Model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mysite.phone_model",
                    ),
                ),
            ],
        ),
    ]
