# Generated by Django 5.0.1 on 2024-03-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0003_phone_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("User_account", models.CharField(max_length=20)),
                ("User_password", models.CharField(max_length=20)),
            ],
        ),
    ]
