# Generated by Django 5.0.1 on 2024-03-04 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0004_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="phone_product", options={"ordering": ("Model",)},
        ),
    ]
