# Generated by Django 5.0.1 on 2024-04-03 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0006_born111"),
    ]

    operations = [
        migrations.AlterModelOptions(name="born111", options={"ordering": ("id",)},),
    ]
