# Generated by Django 5.0.1 on 2024-04-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0007_alter_born111_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="phone_product",
            name="owner",
            field=models.CharField(default="andy5697", max_length=20),
        ),
    ]
