# Generated by Django 5.0.1 on 2024-04-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0008_phone_product_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone_product",
            name="owner",
            field=models.CharField(max_length=20),
        ),
    ]
