# Generated by Django 5.0.1 on 2024-04-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0010_rename_owner_phone_product_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.CharField(default="judy5566675@gamil.com", max_length=30),
        ),
    ]
