# Generated by Django 5.0.1 on 2024-04-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0011_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="email", field=models.CharField(max_length=30),
        ),
    ]
