# Generated by Django 5.0.1 on 2024-04-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0012_alter_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=30)),
            ],
        ),
    ]
