# Generated by Django 5.0.1 on 2024-04-11 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0013_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mysite.email"
            ),
        ),
    ]
