# Generated by Django 5.0.1 on 2024-05-02 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0018_users_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Phone_Product2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Description", models.CharField(max_length=200)),
                ("Price", models.PositiveIntegerField()),
                ("Quantity", models.PositiveIntegerField()),
                ("Img", models.ImageField(upload_to="image/")),
                ("Owner", models.CharField(max_length=20)),
                (
                    "Model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mysite.phone_model",
                    ),
                ),
            ],
            options={"ordering": ("Model",),},
        ),
    ]
