# Generated by Django 5.0.1 on 2024-05-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0019_phone_product2"),
    ]

    operations = [
        migrations.CreateModel(
            name="phone_cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("User_account", models.CharField(max_length=20)),
                ("pid", models.PositiveIntegerField()),
            ],
            options={"ordering": ("User_account",),},
        ),
    ]
