# Generated by Django 5.0.1 on 2024-05-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0021_phone_shopped"),
    ]

    operations = [
        migrations.CreateModel(
            name="phone_shopped2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("User_account", models.CharField(max_length=20)),
                ("pid", models.PositiveIntegerField()),
                ("quantity", models.PositiveIntegerField()),
                ("address", models.CharField(max_length=50)),
                ("phone_number", models.CharField(max_length=10)),
            ],
            options={"ordering": ("pid",),},
        ),
    ]
