# Generated by Django 5.0.1 on 2024-05-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0022_phone_shopped2"),
    ]

    operations = [
        migrations.AddField(
            model_name="phone_shopped2",
            name="paid",
            field=models.CharField(default="No", max_length=5),
        ),
    ]
